name = "HYDE 3.3"

description = '''
The HYDE 3.3 dataset provides historical reconstructions of population dynamics,
urbanization, and land use spanning the past 12,000 years. This dataset includes
gridded estimates of total population, rural and urban population, cropland,
grazing land, and urban area, covering the period from 10,000 BCE to the present.

The data is provided in NetCDF format, with annual time steps for recent centuries
and coarser time intervals for earlier periods. These estimates are based on
archaeological data, historical records, and modern statistical models.
'''

cite = ["KleinGoldewijk2010", "KleinGoldewijk2017", "KleinGoldewijk2023"]
license = "CC BY 4.0"
